// script.js - Advanced Fraud Detection System

document.addEventListener("DOMContentLoaded", () => {
    const connectWalletBtn = document.getElementById("connectWallet");
    const walletAddressSpan = document.getElementById("walletAddress");
    const walletStatus = document.getElementById("walletStatus");
    const checkFraudBtn = document.getElementById("checkFraud");
    const verifyBlockchainBtn = document.getElementById("verifyBlockchain");
    const aiAnalyzeBtn = document.getElementById("aiAnalyze");
    const voteFraudBtn = document.getElementById("voteFraud");
    const voteClearBtn = document.getElementById("voteClear");
    const flagFraudBtn = document.getElementById("flagFraud");
    const generateReportBtn = document.getElementById("generateReport");

    let web3;

    // Connect Wallet Function
    async function connectWallet() {
        if (window.ethereum) {
            web3 = new Web3(window.ethereum);
            try {
                const accounts = await ethereum.request({ method: 'eth_requestAccounts' });
                walletAddressSpan.textContent = accounts[0];
                walletStatus.textContent = "🟢 Connected";
            } catch (error) {
                console.error("User denied wallet connection");
            }
        } else {
            alert("Please install MetaMask!");
        }
    }
    connectWalletBtn.addEventListener("click", connectWallet);

    // Fraud Analysis Function
    function analyzeFraud() {
        const transactionID = document.getElementById("transactionID").value;
        if (!transactionID) return alert("Enter a transaction ID");

        const isFraud = Math.random() < 0.3; // Simulated AI detection
        document.getElementById("fraudResult").textContent = isFraud ? "🚨 Fraudulent Transaction Detected!" : "✅ Transaction is Safe";
    }
    checkFraudBtn.addEventListener("click", analyzeFraud);

    // Blockchain Verification Function
    function verifyOnBlockchain() {
        const txID = document.getElementById("blockchainTxID").value;
        if (!txID) return alert("Enter a transaction hash");
        
        document.getElementById("blockchainResult").textContent = "🔄 Fetching data from blockchain...";
        setTimeout(() => {
            document.getElementById("blockchainResult").textContent = "✅ Transaction Verified on Blockchain";
        }, 2000);
    }
    verifyBlockchainBtn.addEventListener("click", verifyOnBlockchain);

    // AI Fraud Risk Scoring
    function aiFraudRiskAnalysis() {
        const aiTxID = document.getElementById("aiTxID").value;
        if (!aiTxID) return alert("Enter transaction ID for AI analysis");

        const riskScore = Math.floor(Math.random() * 100);
        document.getElementById("aiRiskResult").textContent = `⚠️ AI Risk Score: ${riskScore}%`;
    }
    aiAnalyzeBtn.addEventListener("click", aiFraudRiskAnalysis);

    // Investigator Voting System
    function investigatorVote(isFraud) {
        const investigatorTxID = document.getElementById("investigatorTxID").value;
        if (!investigatorTxID) return alert("Enter transaction ID to vote");
        
        document.getElementById("investigatorVoteResult").textContent = isFraud ? "🚨 Marked as Fraud!" : "✅ Marked as Safe!";
    }
    voteFraudBtn.addEventListener("click", () => investigatorVote(true));
    voteClearBtn.addEventListener("click", () => investigatorVote(false));

    // Fraud Flagging System
    function flagFraud() {
        const txID = document.getElementById("flagTransactionID").value;
        const reason = document.getElementById("flagReason").value;
        if (!txID || !reason) return alert("Enter transaction ID and reason");
        
        document.getElementById("flagResult").textContent = `🚩 Fraud Flagged: ${reason}`;
    }
    flagFraudBtn.addEventListener("click", flagFraud);

    // Generate Fraud Report
    function generateReport() {
        const reportContent = "Fraud Detection Report\n\n- Transactions Checked: 100\n- Fraudulent Transactions: 30\n- AI Risk Scores: Various\n\nGenerated by Fraud Detection System.";
        const blob = new Blob([reportContent], { type: "text/plain" });
        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = "Fraud_Report.txt";
        link.click();
    }
    generateReportBtn.addEventListener("click", generateReport);

    // Live Fraud Analytics Chart
    const ctx = document.getElementById("fraudChart").getContext("2d");
    new Chart(ctx, {
        type: "doughnut",
        data: {
            labels: ["Fraudulent", "Safe"],
            datasets: [{
                data: [30, 70],
                backgroundColor: ["red", "green"]
            }]
        }
    });

    // Fraud Trend Analysis Chart
    const trendCtx = document.getElementById("fraudTrendChart").getContext("2d");
    new Chart(trendCtx, {
        type: "line",
        data: {
            labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
            datasets: [{
                label: "Fraud Cases",
                data: [5, 10, 20, 15, 25, 30],
                borderColor: "red",
                fill: false
            }]
        }
    });

    // Real-Time Alerts
    function showAlert(message) {
        const alertBox = document.getElementById("alertBox");
        const alert = document.createElement("div");
        alert.textContent = message;
        alert.className = "alert";
        alertBox.appendChild(alert);
        setTimeout(() => alert.remove(), 5000);
    }

    // Simulate Fraud Alerts
    setInterval(() => {
        const alerts = ["🚨 Suspicious transaction detected!", "⚠️ High AI Risk Score Transaction!", "🚩 Investigator flagged a transaction!"];
        const randomAlert = alerts[Math.floor(Math.random() * alerts.length)];
        showAlert(randomAlert);
    }, 10000);
});
